version: '3.8'

services:
  web:
    build: .
    container_name: gestor_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gestor_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestor_tarefas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
